name: Node.js Package
on:
  create:
    tags:
      - v[0-9].[0-9]+.[0-9]+
jobs:
  build:
    name: Push npm package to github registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@postgood-dev'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Prepare notify
        env:
          GITHUB_JOB_STATUS: ${{ needs.build.result }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/notify.sh"
          "${GITHUB_WORKSPACE}/.github/scripts/notify.sh"

      - name: Send telegram message on Deploy
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.NOTIFY_TELEGRAM_TO }}
          token: ${{ secrets.NOTIFY_TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>Scrapper</b>

            Статус: <b>${{ env.GITHUB_JOB_STATUS_EMOJI }} ${{ needs.build.result }}</b>
            Версия: ${{ github.ref_name }}
            Репо: <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>



