name: Node.js Package
on:
  create:
    tags:
      - v[0-9].[0-9]+.[0-9]+
jobs:
  build:
    name: Push npm package to github registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@postgood-dev'
      - run: yarn --frozen-lockfile
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
